# Generated by Django 3.0.4 on 2022-03-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('id',)},
        ),
    ]
