# Generated by Django 3.0.4 on 2022-03-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_article_top_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.BinaryField()),
                ('progress', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
