# Generated by Django 3.0.4 on 2022-02-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('completed', models.BooleanField(default=False)),
                ('group', models.CharField(default='未分类', max_length=20)),
                ('text', models.CharField(default='none', max_length=200)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SubTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('completed', models.BooleanField(default=False)),
                ('group', models.CharField(default='未分类', max_length=20)),
                ('text', models.CharField(default='none', max_length=200)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTodo', to='todo.Todo')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SSubTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('completed', models.BooleanField(default=False)),
                ('group', models.CharField(default='未分类', max_length=20)),
                ('text', models.CharField(default='none', max_length=200)),
                ('subtodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssubTodo', to='todo.Todo')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
