# Generated by Django 3.0.4 on 2022-01-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('cid',)},
        ),
        migrations.CreateModel(
            name='Recitedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='easy or diff?')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Card')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
