# Generated by Django 3.0.4 on 2022-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_wordlist_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='len_list',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
