# Generated by Django 3.0.4 on 2022-02-24 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20220129_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='card',
            name='cid',
        ),
        migrations.AddField(
            model_name='card',
            name='due',
            field=models.DateTimeField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='card',
            name='forget_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='ratio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='review_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
