# Generated by Django 3.0.4 on 2022-02-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='name',
        ),
    ]
