# Generated by Django 3.0.4 on 2022-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_remove_dict_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='current_group',
            field=models.CharField(default='{}', max_length=1000),
        ),
    ]
