# Generated by Django 3.0.4 on 2022-03-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_recitedata_last_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recitedata',
            old_name='last_params',
            new_name='params',
        ),
    ]
