# Generated by Django 3.0.4 on 2022-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0017_auto_20220309_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='coca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recitedata',
            name='params',
            field=models.CharField(default='{}', max_length=20000),
        ),
    ]
